pack.add({
	{
		src = "github.com/kimpure/transparent.nvim",
		boot = {
			"transparent",
			groups = {
				"Normal",
				"NormalNC",
				"Comment",
				"Constant",
				"Special",
				"Identifier",
				"Statement",
				"PreProc",
				"Type",
				"Underlined",
				"Todo",
				"String",
				"Function",
				"Conditional",
				"Repeat",
				"Operator",
				"Structure",
				"LineNr",
				"NonText",
				"SignColumn",
				"CursorLine",
				"CursorLineNr",
				"StatusLine",
				"StatusLineNC",
				"EndOfBuffer",
				"WinSeparator",
				"MsgArea",
				"Pmenu",
				"PmenuSel",

				"NeoTreeNormal",
				"NeotreeNormalNC",
				"NvimTreeNormal",

				"SatelliteBar",
				"SatelliteBackground",
			},
		},
	},
})
